service: sms-notification
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
functions:
  send_sms:
    handler: handler.send
    events:
      - sqs:  ${ssm:${self:custom.stage}-sms-sqs}
    role:  ${ssm:${self:custom.stage}-sms-iam-role}
    environment:
      MESSAGE_BIRD_API_KEY: ${ssm:${self:custom.stage}-message-bird-api-key}
      SMS_PHONE_FROM: ${ssm:${self:custom.stage}-sms-phone-from}
      SMS_PHONE_TO: ${ssm:${self:custom.stage}-sms-phone-to}

custom:
  stage: ${opt:stage, self:provider.stage}